table Dim_date
	lineageTag: 78ffc907-a7ff-40b8-a935-edadfce50c41

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aae72c6c-bfec-4b33-b930-892aa53b03ac
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f2ac503a-3356-4ec3-9912-54920c6c8236
			defaultHierarchy: LocalDateTable_d1935663-7044-429a-9679-c35e7dfaf5fd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9921ec88-1543-49b4-ad22-7bac6ebb33a5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: de963b4b-49a1-4516-9778-df250103b6a6
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition Dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vibusha\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Inserted Year" = Table.AddColumn(#"Removed Duplicates", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([date]), Int64.Type)
				in
				    #"Inserted Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

