table Fact_sales
	lineageTag: 1cab0d94-536a-4ac4-942b-d98753147cc9

	measure 'Total Sales' = SUM(Fact_sales[sales_amount])

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 4b12d8b3-7bac-4242-a199-518e2c9d4f89
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc44cb7b-b6ba-4e3f-b4df-2baa0fc74d8a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 7cefb672-f6f7-4667-a768-14486bc0b9be
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 8f03414d-9aa6-4cd8-8a47-4a257e5fd63a
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 8b140f85-318e-43f4-a1af-90288e455450
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 0f332fe6-bce5-458d-9915-1e40f1da730f
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: e1ba4e30-64b8-4920-b65e-3c67c7bfbc7f
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 20646d80-2828-4faf-a31e-0fa26799ea11
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: b792a132-d088-4890-91a2-f793394c844f
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Sales Growth %' =
		VAR CurrentMonthSales = [Total Sales]
		VAR PreviousMonthSales =
			CALCULATE(
				[Total Sales],
				DATEADD(Dim_date[date], -1, MONTH)
			)
		RETURN
			DIVIDE(
				CurrentMonthSales - PreviousMonthSales,
				PreviousMonthSales
			)

	measure 'Running Total Sales' =
		VAR CurrentDate = MAX(Dim_date[date])
		RETURN
			CALCULATE(
				[Total Sales],
				FILTER(
					ALL(Dim_date),
					Dim_date[date] <= CurrentDate
				)
			)

	measure 'City Sales Rank' =
		RANKX(
			ALL(Dim_city[city]),
			[Total Sales],
			,
			DESC,
			Dense
		)

	partition Fact_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vibusha\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
